name: Test and lint
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t test --target dev .

      - name: Test
        run: docker run --rm -v $PWD:/app test python -m pytest

      - name: Lint
        run: docker run --rm -v $PWD:/app test pylint pid_service/

      - name: Typecheck
        run: docker run --rm -v $PWD:/app test mypy --ignore-missing-imports pid_service/
