name: Test and lint
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t test --target test .

      - name: Test
        run: docker run --rm -v $PWD:/app test pytest

      - name: Lint
        run: docker run --rm -v $PWD:/app test pylint **/*.py --errors-only --ignored-modules=netCDF4

      - name: Typecheck
        run: docker run --rm -v $PWD:/app test mypy --ignore-missing-imports pid_service scripts
